title: Site

pages:
  template:
    - cycle
  sort: from desc
  num: date


fields:
  title:
    label: Title
    type:  text

  author:
    label: Author
    type:  text

  description:
    label: Description
    type:  textarea
    
  copyright:
    label: Copyright
    type:  textarea
